# Generated by Django 6.0.3 on 2026-04-10 09:55

import apps.MapsBORA.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapper_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('map_name', models.CharField(max_length=300)),
                ('map_url', models.URLField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(max_length=400)),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
                ('gpx_file', models.FileField(blank=True, help_text="Optional: Send the course's .gpx", null=True, upload_to=apps.MapsBORA.models.get_gpx_path)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ['request_date'],
            },
        ),
    ]
