# Generated by Django 6.0.3 on 2026-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapsBORA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapper_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('map_name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=400)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'ordering': ['submitted_date'],
            },
        ),
        migrations.DeleteModel(
            name='Submissao',
        ),
    ]
